# Generated by Django 4.2 on 2025-03-06 06:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_alter_ordercase_shipping_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcases',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Image must be 490px by 200px.', keep_meta=True, null=True, quality=75, scale=None, size=[490, 200], upload_to='payments/case_images/'),
        ),
    ]
