# Generated by Django 4.2 on 2025-06-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_userorderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userPaymentHistory',
        ),
    ]
