# Generated by Django 4.2 on 2025-03-06 06:07

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Image must be 200px by 200px.', keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
    ]
