# Generated by Django 4.2 on 2025-06-04 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_remindmeupcomingevent_is_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedAsReadRemindMeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='events.remindmeupcomingevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
