# Generated by Django 4.2 on 2025-06-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_markedasreadremindmenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindmeupcomingevent',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
