# Generated by Django 4.2 on 2025-04-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0015_alter_usermanual_published_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonyofsalvation',
            name='testimony_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimony/'),
        ),
        migrations.AlterField(
            model_name='testimonyofsalvation',
            name='link',
            field=models.URLField(blank=True, help_text='A video that come from YouTube', null=True),
        ),
    ]
