# Generated by Django 4.2 on 2025-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_fatherofrepentancelists_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralServicesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the applicant', max_length=255)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True)),
                ('address', models.TextField(help_text='Address of the applicant')),
                ('deceased_full_name', models.CharField(help_text='Full name of the deceased', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Age of the deceased')),
                ('date_of_passing', models.DateField(help_text='Date of passing')),
                ('place_of_death', models.CharField(help_text='Place where the deceased passed away', max_length=255)),
                ('preferred_date', models.DateField(help_text='Preferred date for the funeral service')),
                ('church_name', models.CharField(help_text='Name of the church where the service will be held', max_length=255)),
                ('additional_requests', models.TextField(blank=True, help_text='Any additional requests or details', null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates whether the required payment has been made')),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier for the application', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time the application was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time the application was last updated')),
            ],
        ),
    ]
