# Generated by Django 4.2 on 2025-01-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_funeralservicesapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralservicesapplication',
            name='location_preferred',
            field=models.CharField(blank=True, help_text='location preferred where the service will be held', max_length=255, null=True),
        ),
    ]
