# Generated by Django 4.2 on 2025-05-01 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marriage', '0013_alter_coursechapterprogresscontroller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetevents',
            name='status',
        ),
        migrations.AddField(
            model_name='meetevents',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetevents',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetevents',
            name='cancelled_reason',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetevents',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetevents',
            name='status_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
